repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push]